# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='Содержимое')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=16, verbose_name='Название')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=512, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('publisher', models.CharField(default='', max_length=32, verbose_name='Издатель')),
                ('bought', models.FloatField(default=0, verbose_name='Закупочная цена')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('discount', models.FloatField(default=1.0, verbose_name='Множитель скидки')),
                ('quantity', models.IntegerField(default=0, null=True, verbose_name='Количество')),
                ('weight', models.FloatField(default=100, verbose_name='Вес')),
                ('cover_list', models.TextField(default='', verbose_name='Список обложек')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('session_timestamp', models.FloatField(null=True, verbose_name='Сессия')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.Category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='Содержимое')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.DeliveryMethod', verbose_name='Метод доставки')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.PaymentMethod', verbose_name='Метод оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='Пользователь'),
        ),
    ]
