# Generated by Django 2.0b1 on 2017-10-26 23:44

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', jsonfield.fields.JSONField(default='', verbose_name='Содержимое')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Корзины',
                'verbose_name': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=16, verbose_name='Название')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.Category')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Методы доставки',
                'verbose_name': 'Метод доставки',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=512, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('publisher', models.CharField(default='', max_length=32, verbose_name='Издатель')),
                ('bought', models.FloatField(default=0, verbose_name='Закупочная цена')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('discount', models.FloatField(default=1.0, verbose_name='Множитель скидки')),
                ('quantity', models.IntegerField(default=0, null=True, verbose_name='Количество')),
                ('weight', models.FloatField(default=100, verbose_name='Вес')),
                ('cover_list', jsonfield.fields.JSONField(default='', verbose_name='Список обложек')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', jsonfield.fields.JSONField(default='', verbose_name='Содержимое')),
                ('track_code', models.CharField(default='', max_length=32, verbose_name='Код отслеживания')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.DeliveryMethod', verbose_name='Метод доставки')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=128, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Статусы заказа',
                'verbose_name': 'Статус заказа',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Методы оплаты',
                'verbose_name': 'Метод оплаты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.PaymentMethod', verbose_name='Метод оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.OrderStatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.User', verbose_name='Пользователь'),
        ),
    ]
