# Generated by Django 2.0b1 on 2017-10-27 19:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='content',
            field=jsonfield.fields.JSONField(default='[]', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_code',
            field=models.CharField(max_length=32, null=True, verbose_name='Код отслеживания'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Описание'),
        ),
    ]
