# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=16, verbose_name='Краткое имя')),
                ('full_name', models.CharField(default='', max_length=32, verbose_name='Полное имя')),
                ('parser_data', models.TextField(default='', verbose_name='Данные для парсера')),
            ],
        ),
    ]
