# Generated by Django 2.0.2 on 2018-04-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cover_list',
        ),
        migrations.AddField(
            model_name='item',
            name='cover_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Адрес обложки'),
        ),
    ]
