# Generated by Django 2.0.2 on 2018-04-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20180406_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Полное название')),
                ('abbreviature', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Аббревиатура')),
                ('midtown_code', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Код Midtown')),
                ('load_weekly', models.BooleanField(default=True, verbose_name='Недельный')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.Category', verbose_name='Категория')),
            ],
        ),
    ]
