# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.RemoveField(
            model_name='item',
            name='session_timestamp',
        ),
    ]
