# Generated by Django 2.0b1 on 2017-11-03 03:31

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20171027_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='content',
            field=django_mysql.models.JSONField(default=list, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cover_list',
            field=django_mysql.models.JSONField(default='', verbose_name='Список обложек'),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=django_mysql.models.JSONField(default=list, verbose_name='Содержимое'),
        ),
    ]
