# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:36
from __future__ import unicode_literals

import commerce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20170827_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='content',
            field=commerce.models.JSONField(default='', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cover_list',
            field=commerce.models.JSONField(default='', verbose_name='Список обложек'),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=commerce.models.JSONField(default='', verbose_name='Содержимое'),
        ),
    ]
