# Generated by Django 2.0.2 on 2018-04-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
        migrations.AlterField(
            model_name='item',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.Publisher', verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Краткое название'),
        ),
    ]
