# Generated by Django 2.0b1 on 2017-11-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20171114_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
