# Generated by Django 2.0.2 on 2018-07-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20180714_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='ID обложки'),
        ),
    ]
