# Generated by Django 2.0b1 on 2017-11-16 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20171115_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.Item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bought',
            field=models.FloatField(blank=True, default=0, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cover_list',
            field=django_mysql.models.JSONField(blank=True, default='', verbose_name='Список обложек'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(blank=True, default=1.0, verbose_name='Множитель скидки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, default='Без названия', max_length=512, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, default=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=django_mysql.models.JSONField(blank=True, default=list, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.DeliveryMethod', verbose_name='Метод доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.PaymentMethod', verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.OrderStatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Код отслеживания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Название'),
        ),
    ]
