# Generated by Django 2.0b1 on 2017-11-16 02:58

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_auto_20171116_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover_list',
            field=django_mysql.models.JSONField(blank=True, default=dict, verbose_name='Список обложек'),
        ),
    ]
