# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0003_auto_20170827_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commerce.Item')),
                ('price_origin', models.FloatField(default=0.0, verbose_name='Оригинальная цена')),
                ('diamond_code', models.CharField(max_length=16, null=True, verbose_name='Код Diamond')),
                ('release_date', models.DateField(default='1970-01-01', verbose_name='Дата выхода')),
            ],
            bases=('commerce.item',),
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('preview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='previews.Preview')),
                ('discount_superior', models.FloatField(default=1.0, verbose_name='Множитель скидки Superior')),
            ],
            bases=('previews.preview',),
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('preview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='previews.Preview')),
                ('midtown_id', models.CharField(default='', max_length=16, verbose_name='Код Midtown')),
            ],
            bases=('previews.preview',),
        ),
    ]
