# Generated by Django 2.0.2 on 2018-02-06 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commerce.Item')),
                ('price_origin', models.FloatField(default=0.0, verbose_name='Оригинальная цена')),
                ('diamond_id', models.CharField(max_length=16, null=True, verbose_name='ID Diamond')),
                ('release_date', models.DateField(default='1970-01-01', verbose_name='Дата выхода')),
                ('session_timestamp', models.FloatField(default=0.0, verbose_name='Сессия')),
            ],
            bases=('commerce.item',),
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('preview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='previews.Preview')),
                ('discount_superior', models.FloatField(default=1.0, verbose_name='Множитель скидки superior')),
            ],
            bases=('previews.preview',),
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('preview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='previews.Preview')),
                ('midtown_id', models.CharField(default='', max_length=16, verbose_name='Код Midtown')),
            ],
            bases=('previews.preview',),
        ),
    ]
