# Generated by Django 2.0.2 on 2018-02-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='diamond_id',
            field=models.CharField(max_length=64, null=True, verbose_name='ID Diamond'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='midtown_id',
            field=models.CharField(default='', max_length=64, verbose_name='Код Midtown'),
        ),
    ]
