# Generated by Django 2.0.2 on 2018-05-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0002_auto_20180507_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='mode',
            field=models.CharField(choices=[('monthly', 'Месяц'), ('weekly', 'Неделя')], max_length=8, null=True, verbose_name='Тип'),
        ),
    ]
