# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0002_auto_20170903_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='discount_superior',
            field=models.FloatField(default=1.0, verbose_name='Множитель скидки superior'),
        ),
    ]
