# Generated by Django 2.0.2 on 2018-04-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0002_auto_20180302_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preview',
            old_name='session_timestamp',
            new_name='session',
        ),
    ]
