# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0003_auto_20170921_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='session_timestamp',
            field=models.FloatField(default=0.0, verbose_name='Сессия'),
        ),
    ]
