# Generated by Django 2.0.2 on 2018-07-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previews', '0003_auto_20180507_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='cover_origin',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Оригинальнаый адрес обложки'),
        ),
    ]
