# Generated by Django 2.0b1 on 2017-10-26 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=32, verbose_name='Страна')),
                ('region', models.CharField(default='', max_length=128, verbose_name='Регион')),
                ('locality', models.CharField(default='', max_length=64, verbose_name='Населенный пункт')),
                ('street', models.CharField(default='', max_length=256, verbose_name='Улица')),
                ('building', models.CharField(default='', max_length=32, verbose_name='Дом, строение, корпус')),
                ('apartment', models.CharField(max_length=8, null=True, verbose_name='Квартира, комната')),
                ('zipcode', models.CharField(default='', max_length=8, verbose_name='Почтовый индекс')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='', max_length=128, unique=True, verbose_name='Адрес электронной почты')),
                ('status', models.SmallIntegerField(default=4, verbose_name='Статус')),
                ('last_name', models.CharField(default='', max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(default='', max_length=128, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=128, verbose_name='Отчество')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Address', verbose_name='Адрес')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
