# Generated by Django 2.0.2 on 2019-01-04 19:52

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(default='', max_length=128, unique=True, verbose_name='Адрес электронной почты')),
                ('status', models.SmallIntegerField(default=4, verbose_name='Статус')),
                ('last_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='', max_length=128, verbose_name='Отчество')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Администратор')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=True, verbose_name='Основной')),
                ('country', models.CharField(default='', max_length=32, verbose_name='Страна')),
                ('region', models.CharField(default='', max_length=128, verbose_name='Регион')),
                ('locality', models.CharField(default='', max_length=64, verbose_name='Населенный пункт')),
                ('street', models.CharField(default='', max_length=256, verbose_name='Улица')),
                ('building', models.CharField(default='', max_length=32, verbose_name='Дом, строение, корпус')),
                ('apartment', models.CharField(blank=True, max_length=8, null=True, verbose_name='Квартира, комната')),
                ('zipcode', models.CharField(default='', max_length=8, verbose_name='Почтовый индекс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
