# Generated by Django 2.0b1 on 2017-10-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171027_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Квартира, комната'),
        ),
    ]
