# Generated by Django 2.0b1 on 2017-10-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171027_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=128, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
