#!/bin/bash
# Gunicorn pidfile is at /tmp/edgecomics.pid

if [ -f /tmp/edgecomics.pid ]; then
	echo -e '\033[1;31mGunicorn is already running\033[0m'
else
	gunicorn edgecomics.wsgi:application -c gunicorn.py
	sleep 1

	if [ -f /tmp/edgecomics.pid ]; then
		echo -n
	else
		echo -e '\033[1;31mAn error has occured while starting Gunicorn\033[0m'
	fi
fi
